<table>
<tr>
<td><img src="https://www.institutobme.es/dam/layout/bme-logo.svg" width="150"></td>
<td><table><tr><td><h1>Carpetas y ficheros</h1></td></tr>
           <tr><td><h3>Rafael Caballero Roldán</h3></td></tr></table></td>

</tr>
</table>




### Índice
[Caminos](#Caminos)<br>
[Creación de carpetas](#Creación_de_carpetas)<br>
[Borrado](#Borrado)<br>
[Copia de ficheros](#Copia)<br>
[Ficheros .zip](#Zip)<br>

## Preparación

Ejecutar las dos siguientes celdas para asegurar que las bibliotecas que vamosa  usar están cargadas, y también para crear un par de ficheros de prueba

In [1]:
modules = ["pathlib", "shutil", "pandas", "numpy","pyarrow"]

import sys
import os.path
from subprocess import check_call
import importlib
import os

def instala(modules):
  print("Instalando módulos")
  for m in modules:
      # para el import quitamos [...] y ==...
      p = m.find("[")
      mi = m if p==-1 else m[:p]
      p = mi.find("==")
      mi = mi if p==-1 else mi[:p]

      torch_loader = importlib.util.find_spec(mi)
      if torch_loader is not None:
          print(m," encontrado")
      else:
          print(m," No encontrado, instalando...",end="")  
          try:        
            r = check_call([sys.executable, "-m", "pip", "install", "--user", m])
            print("¡hecho!")
          except:
            print("¡Problema al instalar ",m,"! ¿seguro que el módulo existe?",sep="")
              
  print("¡Terminado!")

instala(modules)

Instalando módulos
pathlib  encontrado
shutil  encontrado
pandas  encontrado
numpy  encontrado
pyarrow  encontrado
¡Terminado!

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
path = Path.cwd() 

# datos
numcolumnas = 100
filas = []
numfilas = 10000
for i in range(numfilas):
    filas.append(np.random.randint(1,5000,numcolumnas))

df = pd.DataFrame(filas, columns = ["c"+str(i) for i in range(numcolumnas)])
fichero_csv = path / "prueba.csv"
fichero_parquet = path / "prueba.parquet"
df.to_csv(fichero_csv,index=False)
df.to_parquet(fichero_parquet, index=False)

<a name="Caminos"></a>
#### Caminos

En cualquier sistema operativo los sistemas de almacenamiento permanentes (discusos, memorias flash, etc) van a tener un sistema de carpetas y ficheros:
    
    * Las carpetas pueden contener ficheros y otras carpetas
    * Los ficheros contienen datos


El camino a un fichero se puede dar de dos formas:

#### Camino Absoluto

Ejemplo  **d:\docencia\2526\apd\codigo\path.ipynb**

Estos caminos comienzan generalmente por el nombre de unidad, luego la secuencia de carpetas y finalmente el nombre del fichero con su extensión. 

En el caso de Windows el separador de elementos es \ y en el caso de linux es /. Como la \ es un símbolo especial suele dar problemas, por eso Python incluye el prefijo r para poder usarlo:

        camino = r"c:\bertoldo\ficheros\datos.csv"

#### Camino Relativo

Se mueve desde el lugar en el que estamos (en el caso de un notebook sería desde el lugar donde está el notebook). Se utilia
- . Para indicar la carpeta actual como  **.\img\log.png**: que significa: busca dentro de la carpeta actual (.) una carpeta img y dentro de img el fichero log.png
- .. Para indicar el antecesor de la carpetaa anterior. Por ejemplo **..\datos\trafico.csv**, que indica que la carpeta datos es "hermana" de la actual

    
Debemos ser capaces de manejar estas estructuras en Python para automatizar nuestro proceso de adquisición de datos.

Primero veamos en qué carpeta nos encontramos ahora mismo (la del notebook de Python)

In [3]:
from pathlib import Path
path = Path.cwd()  
print(path)

c:\rafa\docencia\2526\apd\codigo

Añadimos un fichero al final del camino

In [4]:
import pandas as pd
df = pd.DataFrame({"nombre":["Bertoldo", "Herminia","Calixta","Aniceto"],"edad":[18,19,24,30]})
p =  path / "datos.csv"             # Alternativa: Path(path,"datos.csv")
df.to_csv(p,index=False)
print(p)

c:\rafa\docencia\2526\apd\codigo\datos.csv

¿El path existe? ¿es una carpeta o un fichero?

In [5]:
if p.exists():
    print(p,"existe",end=" ")
    if p.is_dir():
        print("y es una carpeta")
    else:
        if p.is_file():
            print("y es un fichero")
else:
    print(p,"no existe")

c:\rafa\docencia\2526\apd\codigo\datos.csv existe y es un fichero

Ya sabemos que p es un camino a un fichero, ahora vamos a ver algunas de sus características

In [6]:
p.absolute

In [7]:
p.drive

'c:'

In [8]:
p.parent

WindowsPath('c:/rafa/docencia/2526/apd/codigo')

In [9]:
p.name

'datos.csv'

In [10]:
p.stem

'datos'

In [11]:
p.suffix

'.csv'

Además podemos obtener [algunos datos](https://docs.python.org/3/library/os.html#os.stat_result) del fichero, por ejemplo su tamaño en bytes

In [12]:
estad = p.stat() # estadísticas varias
estad

os.stat_result(st_mode=33206, st_ino=72902018968060445, st_dev=4655120325201049254, st_nlink=1, st_uid=0, st_gid=0, st_size=63, st_atime=1771924148, st_mtime=1771924148, st_ctime=1771841335)

In [13]:
estad.st_size

63

¿Y si no sé cómo se llama el fichero?

Todas las carpetas y ficheros del path actual (que debe ser una carpeta)

In [14]:
def lista(path):
    print(path)
    espacio = " "*5
    for p in path.iterdir():
        if p.is_dir():
            print(espacio,p.name,": carpeta",sep="")
        else:
            if p.is_file():
                print(espacio,p.name,": fichero",sep="")
    print("="*40)
                
lista(path)

c:\rafa\docencia\2526\apd\codigo
     accidentes.xlsx: fichero
     BeautifulSoup.ipynb: fichero
     carga.ipynb: fichero
     control.ipynb: fichero
     dataframes.ipynb: fichero
     dataframesCompletado.ipynb: fichero
     datos.csv: fichero
     estructuras.ipynb: fichero
     examenes1D.pdf: fichero
     examenes26.pdf: fichero
     fechas.ipynb: fichero
     informe24.pdf: fichero
     intro.ipynb: fichero
     numpy.ipynb: fichero
     pagina.html: fichero
     paises.csv: fichero
     parocomunidades.csv: fichero
     paths.ipynb: fichero
     prueba.csv: fichero
     prueba.parquet: fichero
     raw: carpeta
     resumen.pdf: fichero
     selenium.ipynb: fichero
     series.ipynb: fichero
     web.ipynb: fichero
========================================

También se puede usar `glob` que tiene alguna ventaja:

- Permite obtener solo los ficheros/carpetas que cumplan un patrón
- Tiene una versión recursiva que busca también en los hijos (ojo, esto puede hacer que sea lento si se hace en un sistema de ficheros grande)

In [15]:
from pathlib import Path

root = Path.cwd()

# todos los ficheros de la carpeta actual
files = [p for p in root.glob("*") if p.is_file()]

# todos los ficheros de la carpeta actual y descendientes (recursivo)
rfiles = [p for p in root.rglob("*") if p.is_file()]

# solo CSV 
csvs = list(root.glob("*.csv"))

print(f"Esta carpeta tiene ficheros{len(files)} ficheros ({len(rfiles)} si contamos descendientes), de los cuales {len(csvs)} son csvs")

Esta carpeta tiene ficheros24 ficheros (39 si contamos descendientes), de los cuales 4 son csvs

In [30]:
csvs = list(root.glob("./raw/*.csv"))
csvs

[WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/abr_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/ago_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/dic_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/ene_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/feb_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/jul_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/jun_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/mar_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/may_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/nov_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/oct_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/sep_meteo22.csv')]

In [35]:
dfs =  [  pd.read_csv(f,sep=";") for f in csvs]
print(len(dfs))

12

In [34]:
dfs[0]

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,28,79,102,81,28079102_81_98,2022,4,1,2.17,V,...,1.72,V,2.83,V,2.12,V,0.00,N,0.00,N
1,28,79,102,81,28079102_81_98,2022,4,2,2.70,V,...,3.42,V,2.82,V,2.78,V,3.30,V,0.00,N
2,28,79,102,81,28079102_81_98,2022,4,3,2.22,V,...,4.75,V,0.00,N,0.00,N,0.00,N,0.00,N
3,28,79,102,81,28079102_81_98,2022,4,4,5.72,V,...,1.88,V,1.57,V,0.48,V,1.28,V,3.15,V
4,28,79,102,81,28079102_81_98,2022,4,5,2.60,V,...,2.93,V,2.63,V,2.80,V,2.68,V,2.05,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2714,28,79,59,89,28079059_89_98,2022,4,26,0.00,V,...,0.30,V,0.10,V,0.10,V,0.30,V,0.20,V
2715,28,79,59,89,28079059_89_98,2022,4,27,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V
2716,28,79,59,89,28079059_89_98,2022,4,28,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V
2717,28,79,59,89,28079059_89_98,2022,4,29,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V
2718,28,79,59,89,28079059_89_98,2022,4,30,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V

In [36]:
df_grande = pd.concat(dfs)
df_grande

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,28,79,102,81,28079102_81_98,2022,4,1,2.17,V,...,1.72,V,2.83,V,2.12,V,0.00,N,0.00,N
1,28,79,102,81,28079102_81_98,2022,4,2,2.70,V,...,3.42,V,2.82,V,2.78,V,3.30,V,0.00,N
2,28,79,102,81,28079102_81_98,2022,4,3,2.22,V,...,4.75,V,0.00,N,0.00,N,0.00,N,0.00,N
3,28,79,102,81,28079102_81_98,2022,4,4,5.72,V,...,1.88,V,1.57,V,0.48,V,1.28,V,3.15,V
4,28,79,102,81,28079102_81_98,2022,4,5,2.60,V,...,2.93,V,2.63,V,2.80,V,2.68,V,2.05,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,28,79,59,89,28079059_89_98,2022,9,26,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V
1256,28,79,59,89,28079059_89_98,2022,9,27,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V
1257,28,79,59,89,28079059_89_98,2022,9,28,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V
1258,28,79,59,89,28079059_89_98,2022,9,29,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V
1259,28,79,59,89,28079059_89_98,2022,9,30,0.00,V,...,0.00,V,0.00,V,0.00,V,0.00,V,0.00,V

<a name="Creación_de_carpetas"></a>
#### Creación de carpetas

Es un buen hábito tener los datos iniciarles en una carpeta `raw` y dejar los resultados en una carpeta `preprocess`. Para ello debemos ser capaces de crear carpetas si no existen

In [38]:
from pathlib import Path
path = Path.cwd()  
pathraw = Path(path,"../misdatos")
if pathraw.exists():
    print("Ya existe")
else:
    print("No existe, lo creamos")
    pathraw.mkdir()
    if pathraw.exists():
        print("Creado")
    else:
        print("No se puede crear!!")

No existe, lo creamos
Creado

In [40]:
from pathlib import Path
path = Path.cwd()  
for i in range(500):
    pathraw = Path(path,"../misdatos/datos"+str(i))
    if not pathraw.exists():
        pathraw.mkdir()

Si ya existe y no lo comprobamos  da error

In [17]:
#pathraw.mkdir() Si quitamos el comentario

Pero se puede hacer mejor con el atributo exists_ok, que indica que si ya existe no haga nada (y si no lo crea)

In [18]:
pathraw.mkdir(exist_ok=True)

Otro parámetro util para `mkdir` es parents=True, que creará además todos las carpetas intermedias. Esto es muy útil para crear una estructura compleja de ficheros

In [ ]:
folders = ["tururu/download/feb","misdatos/download/mar","misdatos/download/may"] 
for f in folders:
    newFolder = Path(path,f)
    newFolder.mkdir(exist_ok=True,parents=True)

FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'c:\\rafa\\docencia\\2526\\apd\\codigo\\tururu\\download\\feb'

In [45]:
carpeta_inicial = Path.cwd()
carpeta = carpeta_inicial
for i in range(500):
    carpeta = carpeta / ("raw"+str(i))


carpeta

WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw0/raw1/raw2/raw3/raw4/raw5/raw6/raw7/raw8/raw9/raw10/raw11/raw12/raw13/raw14/raw15/raw16/raw17/raw18/raw19/raw20/raw21/raw22/raw23/raw24/raw25/raw26/raw27/raw28/raw29/raw30/raw31/raw32/raw33/raw34/raw35/raw36/raw37/raw38/raw39/raw40/raw41/raw42/raw43/raw44/raw45/raw46/raw47/raw48/raw49/raw50/raw51/raw52/raw53/raw54/raw55/raw56/raw57/raw58/raw59/raw60/raw61/raw62/raw63/raw64/raw65/raw66/raw67/raw68/raw69/raw70/raw71/raw72/raw73/raw74/raw75/raw76/raw77/raw78/raw79/raw80/raw81/raw82/raw83/raw84/raw85/raw86/raw87/raw88/raw89/raw90/raw91/raw92/raw93/raw94/raw95/raw96/raw97/raw98/raw99/raw100/raw101/raw102/raw103/raw104/raw105/raw106/raw107/raw108/raw109/raw110/raw111/raw112/raw113/raw114/raw115/raw116/raw117/raw118/raw119/raw120/raw121/raw122/raw123/raw124/raw125/raw126/raw127/raw128/raw129/raw130/raw131/raw132/raw133/raw134/raw135/raw136/raw137/raw138/raw139/raw140/raw141/raw142/raw143/raw144/raw145/raw146/raw147/raw148/raw149/raw150/raw151/raw152/raw153/raw154/raw155/raw156/raw157/raw158/raw159/raw160/raw161/raw162/raw163/raw164/raw165/raw166/raw167/raw168/raw169/raw170/raw171/raw172/raw173/raw174/raw175/raw176/raw177/raw178/raw179/raw180/raw181/raw182/raw183/raw184/raw185/raw186/raw187/raw188/raw189/raw190/raw191/raw192/raw193/raw194/raw195/raw196/raw197/raw198/raw199/raw200/raw201/raw202/raw203/raw204/raw205/raw206/raw207/raw208/raw209/raw210/raw211/raw212/raw213/raw214/raw215/raw216/raw217/raw218/raw219/raw220/raw221/raw222/raw223/raw224/raw225/raw226/raw227/raw228/raw229/raw230/raw231/raw232/raw233/raw234/raw235/raw236/raw237/raw238/raw239/raw240/raw241/raw242/raw243/raw244/raw245/raw246/raw247/raw248/raw249/raw250/raw251/raw252/raw253/raw254/raw255/raw256/raw257/raw258/raw259/raw260/raw261/raw262/raw263/raw264/raw265/raw266/raw267/raw268/raw269/raw270/raw271/raw272/raw273/raw274/raw275/raw276/raw277/raw278/raw279/raw280/raw281/raw282/raw283/raw284/raw285/raw286/raw287/raw288/raw289/raw290/raw291/raw292/raw293/raw294/raw295/raw296/raw297/raw298/raw299/raw300/raw301/raw302/raw303/raw304/raw305/raw306/raw307/raw308/raw309/raw310/raw311/raw312/raw313/raw314/raw315/raw316/raw317/raw318/raw319/raw320/raw321/raw322/raw323/raw324/raw325/raw326/raw327/raw328/raw329/raw330/raw331/raw332/raw333/raw334/raw335/raw336/raw337/raw338/raw339/raw340/raw341/raw342/raw343/raw344/raw345/raw346/raw347/raw348/raw349/raw350/raw351/raw352/raw353/raw354/raw355/raw356/raw357/raw358/raw359/raw360/raw361/raw362/raw363/raw364/raw365/raw366/raw367/raw368/raw369/raw370/raw371/raw372/raw373/raw374/raw375/raw376/raw377/raw378/raw379/raw380/raw381/raw382/raw383/raw384/raw385/raw386/raw387/raw388/raw389/raw390/raw391/raw392/raw393/raw394/raw395/raw396/raw397/raw398/raw399/raw400/raw401/raw402/raw403/raw404/raw405/raw406/raw407/raw408/raw409/raw410/raw411/raw412/raw413/raw414/raw415/raw416/raw417/raw418/raw419/raw420/raw421/raw422/raw423/raw424/raw425/raw426/raw427/raw428/raw429/raw430/raw431/raw432/raw433/raw434/raw435/raw436/raw437/raw438/raw439/raw440/raw441/raw442/raw443/raw444/raw445/raw446/raw447/raw448/raw449/raw450/raw451/raw452/raw453/raw454/raw455/raw456/raw457/raw458/raw459/raw460/raw461/raw462/raw463/raw464/raw465/raw466/raw467/raw468/raw469/raw470/raw471/raw472/raw473/raw474/raw475/raw476/raw477/raw478/raw479/raw480/raw481/raw482/raw483/raw484/raw485/raw486/raw487/raw488/raw489/raw490/raw491/raw492/raw493/raw494/raw495/raw496/raw497/raw498/raw499')

In [46]:
carpeta.mkdir(parents=True)

FileNotFoundError: [WinError 206] El nombre del archivo o la extensión es demasiado largo: 'c:\\rafa\\docencia\\2526\\apd\\codigo\\raw0\\raw1\\raw2\\raw3\\raw4\\raw5\\raw6\\raw7\\raw8\\raw9\\raw10\\raw11\\raw12\\raw13\\raw14\\raw15\\raw16\\raw17\\raw18\\raw19\\raw20\\raw21\\raw22\\raw23\\raw24\\raw25\\raw26\\raw27\\raw28\\raw29\\raw30\\raw31\\raw32\\raw33\\raw34\\raw35\\raw36\\raw37'

<a name="Borrado"></a>
#### Borrado de carpetas y ficheros

En principio disponemos de dos métodos interesantes   
    
    * path.unlink() borra un fichero
    * path.rmdir() borra una carpeta

In [47]:
from pathlib import Path
path = Path.cwd() 
print("Antes")
lista(path)
fichero_csv = Path(path,"prueba.csv")
fichero_csv.unlink(missing_ok=True) # no da error aunque no exista
print("Después")
lista(path)

Antes
c:\rafa\docencia\2526\apd\codigo
     accidentes.xlsx: fichero
     BeautifulSoup.ipynb: fichero
     carga.ipynb: fichero
     control.ipynb: fichero
     dataframes.ipynb: fichero
     dataframesCompletado.ipynb: fichero
     datos.csv: fichero
     estructuras.ipynb: fichero
     examenes1D.pdf: fichero
     examenes26.pdf: fichero
     fechas.ipynb: fichero
     informe24.pdf: fichero
     intro.ipynb: fichero
     misdatos: carpeta
     numpy.ipynb: fichero
     pagina.html: fichero
     paises.csv: fichero
     parocomunidades.csv: fichero
     paths.ipynb: fichero
     prueba.parquet: fichero
     raw: carpeta
     resumen.pdf: fichero
     selenium.ipynb: fichero
     series.ipynb: fichero
     web.ipynb: fichero
========================================
Después
c:\rafa\docencia\2526\apd\codigo
     accidentes.xlsx: fichero
     BeautifulSoup.ipynb: fichero
     carga.ipynb: fichero
     control.ipynb: fichero
     dataframes.ipynb: fichero
     dataframesCompletado.ipynb: fichero
     datos.csv: fichero
     estructuras.ipynb: fichero
     examenes1D.pdf: fichero
     examenes26.pdf: fichero
     fechas.ipynb: fichero
     informe24.pdf: fichero
     intro.ipynb: fichero
     misdatos: carpeta
     numpy.ipynb: fichero
     pagina.html: fichero
     paises.csv: fichero
     parocomunidades.csv: fichero
     paths.ipynb: fichero
     prueba.parquet: fichero
     raw: carpeta
     resumen.pdf: fichero
     selenium.ipynb: fichero
     series.ipynb: fichero
     web.ipynb: fichero
========================================

En el caso de borrar una carpeta debe estar vacía:

In [49]:
from pathlib import Path
path = Path.cwd() 
raw_dir = path / "raw"
raw_dir.rmdir() #si quitamos el comentario dará error

OSError: [WinError 145] El directorio no está vacío: 'c:\\rafa\\docencia\\2526\\apd\\codigo\\raw'

In [50]:
fichs = list(root.glob("./raw/*"))
fichs

[WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/abr_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/ago_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/dic_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/download'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/ene_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/feb_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/Interpretación_datos_meteorologicos.pdf'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/jul_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/jun_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/mar_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/may_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/nov_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/oct_meteo22.csv'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/readme.txt'),
 WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw/sep_meteo22.csv')]

Si no queremos borrar elemento a elemento y queremos borrar todo un subárbol podemos usar la librería `shutil`

OJO: esto puede borrar el disco duro entero sin preguntar, usar con precaución

In [51]:
raw_dir

WindowsPath('c:/rafa/docencia/2526/apd/codigo/raw')

In [52]:
from shutil import rmtree
rmtree(raw_dir,ignore_errors=True) # para que no dé error si no existe

<a name="Copia"></a>
#### Copia de ficheros
Esta biblioteca también nos permite copiar ficheros de un destino a otro

Primero creamos algunas carpetas y un fichero de prueba

In [53]:
folders = ["raw/download/feb","raw/download/mar","raw/download/may"] 
for f in folders:
    newFolder = path / f
    newFolder.mkdir(exist_ok=True,parents=True)
    
import pandas as pd
df = pd.DataFrame({"nombre":["Bertoldo", "Herminia","Calixta","Aniceto"],"edad":[18,19,24,30]})
p = Path(folders[0]) / "datos.csv"
df.to_csv(p,index=False)
lista(Path(folders[0]))

raw\download\feb
     datos.csv: fichero
========================================

In [55]:
import pathlib
import shutil

print("Antes")
lista(Path(folders[1]))
origen=p
for i in range(500):
    destino= Path(folders[1]) / ("datoscopia"+str(i)+".csv")
    print(origen,destino)
    shutil.copy(origen, destino)
print("después")
lista(Path(folders[1]))

Antes
raw\download\mar
     datoscopia.csv: fichero
========================================
raw\download\feb\datos.csv raw\download\mar\datoscopia0.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia1.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia2.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia3.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia4.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia5.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia6.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia7.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia8.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia9.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia10.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia11.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia12.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia13.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia14.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia15.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia16.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia17.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia18.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia19.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia20.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia21.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia22.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia23.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia24.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia25.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia26.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia27.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia28.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia29.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia30.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia31.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia32.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia33.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia34.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia35.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia36.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia37.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia38.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia39.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia40.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia41.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia42.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia43.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia44.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia45.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia46.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia47.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia48.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia49.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia50.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia51.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia52.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia53.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia54.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia55.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia56.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia57.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia58.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia59.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia60.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia61.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia62.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia63.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia64.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia65.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia66.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia67.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia68.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia69.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia70.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia71.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia72.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia73.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia74.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia75.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia76.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia77.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia78.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia79.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia80.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia81.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia82.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia83.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia84.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia85.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia86.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia87.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia88.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia89.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia90.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia91.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia92.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia93.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia94.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia95.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia96.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia97.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia98.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia99.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia100.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia101.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia102.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia103.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia104.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia105.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia106.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia107.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia108.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia109.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia110.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia111.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia112.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia113.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia114.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia115.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia116.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia117.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia118.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia119.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia120.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia121.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia122.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia123.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia124.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia125.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia126.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia127.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia128.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia129.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia130.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia131.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia132.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia133.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia134.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia135.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia136.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia137.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia138.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia139.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia140.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia141.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia142.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia143.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia144.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia145.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia146.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia147.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia148.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia149.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia150.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia151.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia152.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia153.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia154.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia155.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia156.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia157.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia158.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia159.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia160.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia161.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia162.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia163.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia164.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia165.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia166.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia167.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia168.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia169.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia170.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia171.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia172.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia173.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia174.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia175.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia176.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia177.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia178.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia179.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia180.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia181.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia182.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia183.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia184.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia185.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia186.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia187.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia188.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia189.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia190.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia191.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia192.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia193.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia194.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia195.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia196.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia197.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia198.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia199.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia200.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia201.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia202.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia203.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia204.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia205.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia206.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia207.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia208.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia209.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia210.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia211.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia212.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia213.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia214.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia215.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia216.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia217.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia218.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia219.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia220.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia221.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia222.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia223.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia224.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia225.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia226.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia227.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia228.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia229.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia230.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia231.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia232.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia233.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia234.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia235.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia236.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia237.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia238.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia239.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia240.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia241.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia242.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia243.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia244.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia245.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia246.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia247.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia248.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia249.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia250.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia251.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia252.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia253.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia254.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia255.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia256.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia257.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia258.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia259.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia260.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia261.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia262.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia263.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia264.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia265.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia266.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia267.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia268.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia269.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia270.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia271.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia272.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia273.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia274.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia275.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia276.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia277.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia278.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia279.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia280.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia281.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia282.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia283.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia284.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia285.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia286.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia287.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia288.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia289.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia290.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia291.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia292.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia293.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia294.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia295.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia296.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia297.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia298.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia299.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia300.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia301.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia302.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia303.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia304.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia305.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia306.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia307.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia308.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia309.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia310.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia311.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia312.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia313.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia314.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia315.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia316.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia317.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia318.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia319.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia320.csv
raw\download\feb\datos.csv raw\download\mar\datoscopia321.csv

In [56]:
from shutil import rmtree
rmtree(raw_dir,ignore_errors=True)

<a name="Zip"></a>
#### Ficheros .zip


Primero creamos algunas carpetas y un fichero de prueba

In [58]:
from pathlib import Path
path = Path.cwd() 
download_dir = Path(path,"raw/download")
download_dir.mkdir(exist_ok=True,parents=True)

fichero = "meteo22.zip"
path_fich = Path(download_dir,fichero)

In [59]:
import requests
url = "https://github.com/RafaelCaballero/tdm/blob/master/datos/madrid/meteo22.zip?raw=true"
r = requests.get(url)
if r.status_code==200:
    with open(path_fich, 'wb') as f:
        f.write(r.content) # ahora lo grabamos localmente
    print("Grabado")
else:
    print("Error ",r.status_code)
    
lista(download_dir)

Grabado
c:\rafa\docencia\2526\apd\codigo\raw\download
     meteo22.zip: fichero
========================================

Utilizamos `unpack_archive` que detecta el tipo de compresión y descomprime automáticamente. El primer parámetro es el fichero y el segundo la carpeta donde debe guardarse

In [60]:
import shutil
raw_dir = Path(path,"raw")
shutil.unpack_archive(path_fich, raw_dir)
lista(raw_dir)

c:\rafa\docencia\2526\apd\codigo\raw
     abr_meteo22.csv: fichero
     ago_meteo22.csv: fichero
     dic_meteo22.csv: fichero
     download: carpeta
     ene_meteo22.csv: fichero
     feb_meteo22.csv: fichero
     Interpretación_datos_meteorologicos.pdf: fichero
     jul_meteo22.csv: fichero
     jun_meteo22.csv: fichero
     mar_meteo22.csv: fichero
     may_meteo22.csv: fichero
     nov_meteo22.csv: fichero
     oct_meteo22.csv: fichero
     readme.txt: fichero
     sep_meteo22.csv: fichero
========================================

Para acabar un video corto con algunas ideas sobre nombres y organización de ficheros [https://www.youtube.com/watch?v=YslfY4W-NAg](https://www.youtube.com/watch?v=YslfY4W-NAg)